rename "VM_seqread.pdf" "performance.vmexperiments.seq.pdf"
rename "VM_randread.pdf" "performance.vmexperiments.rand.pdf"

rename "optimizedv2 all iodepth and numjobs combos_seqread_iodepth1_numjobs1.pdf" "performance.hwexperiments.optseq.pdf"
rename "optimizedv2 all iodepth and numjobs combos_randread_iodepth1_numjobs1.pdf" "performance.hwexperiments.optrand.pdf"
rename "optimizedv2 all iodepth and numjobs combos_seqread_iodepth16numjobs1.pdf" "performance.hwexperiments.optseqqueue.pdf"
rename "optimizedv2 all iodepth and numjobs combos_randread_iodepth16numjobs1.pdf" "performance.hwexperiments.optrandqueue.pdf"
rename "optimizedv2 all iodepth and numjobs combos_seqread_iodepth1numjobs16.pdf" "performance.hwexperiments.optseqthreads.pdf"
rename "optimizedv2 all iodepth and numjobs combos_randread_iodepth1numjobs16.pdf" "performance.hwexperiments.optrandthreads.pdf"
rename "optimizedv2 all iodepth and numjobs combos_seqread_iodepth16_numjobs16.pdf" "performance.hwexperiments.optseqthreadsqueue.pdf"
rename "optimizedv2 all iodepth and numjobs combos_randread_iodepth16_numjobs16.pdf" "performance.hwexperiments.optrandthreadsqueue.pdf"

rename "json_throughput_log_seqread_32k_logmsec32iodepth1.pdf" "performance.hwexperiments.seqovertime.pdf"
rename "json_throughput_log_randread_32k_logmsec32iodepth1.pdf" "performance.hwexperiments.randovertime.pdf"
rename "json_throughput_log_seqread_32k_logmsec32iodepth1_boxplot.pdf" "performance.hwexperiments.seqovertimebox.pdf"
rename "json_throughput_log_randread_32k_logmsec32iodepth1_boxplot.pdf" "performance.hwexperiments.randovertimebox.pdf"